### ISSUE TITLE
congratulations!I wonder when your team could open the code.Best wishes!

### ISSUE THREAD

**Issue by JiePaiWs** [pointnerfpp/pointnerfpp.github.io#1]

**Comment by wsunid** [comment]
Yeah, I'm on it! 

ETA is within this week!

**Comment by wsunid** [comment]
Hi, 

I just published the code here! Thanks for your patience!

[code]( https://github.com/pointnerfpp/code)

Let me know if you have any questions! 

All the best, 
Weiwei.

**Comment by JiePaiWs** [comment]
Thank you for your work!Best regrads.



---- Replied Message ----
| From | Weiwei ***@***.***> |
| Date | 10/28/2024 13:30 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [pointnerfpp/pointnerfpp.github.io] congratulations!I wonder when your team could open the code.Best wishes! (Issue #1) |

Hi,

I just published the code here! Thanks for your patience!

code

Let me know if you have any questions!

All the best,
Weiwei.

**Comment by JiePaiWs** [comment]
Thanks again for your amazing work.I wonder if i could translate your paper into Chinese and show in CSDN.Best wishes!



---- Replied Message ----
| From | Weiwei ***@***.***> |
| Date | 10/28/2024 13:30 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [pointnerfpp/pointnerfpp.github.io] congratulations!I wonder when your team could open the code.Best wishes! (Issue #1) |

Closed #1 as completed.

**Comment by wsunid** [comment]
Yes, sure as long as you give the proper citation and copyright. Sent from my iPhoneOn Oct 28, 2024, at 10:45 PM, JiePaiWs ***@***.***> wrote:﻿[CAUTION: Non-UBC Email]
Thanks again for your amazing work.I wonder if i could translate your paper into Chinese and show in CSDN.Best wishes!



---- Replied Message ----
| From | Weiwei ***@***.***> |
| Date | 10/28/2024 13:30 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [pointnerfpp/pointnerfpp.github.io] congratulations!I wonder when your team could open the code.Best wishes! (Issue #1) |

Closed #1 as completed.
